code_cat = { # Assigns a category to each stock code
    "AAL":"Mining",
    "ABF":"Food Producers",
    "ADM":"Nonlife Insurance",
    "AHT":"Support Services",
    "ANTO":"Mining",
    "AV":"Life Insurance",
    "AZN":"Pharmaceuticals & Biotechnology",
    "BA":"Aerospace & Defense",
    "BARC":"Banks",
    "BATS":"Tobacco",
    "BDEV":"Household Goods & Home Construction",
    "BKG":"Household Goods & Home Construction",
    "BLND":"Real Estate Investment Trusts",
    "BLT":"Mining",
    "BNZL":"Support Services",
    "BP":"Oil & Gas Producers",
    "BRBY":"Personal Goods",
    "BTA":"Fixed Line Telecommunications",
    "CCH":"Beverages",
    "CCL":"Travel & Leisure",
    "CNA":"Gas, Water & Multiutilities",
    "CPG":"Travel & Leisure",
    "CRDA":"Chemicals",
    "CRH":"Construction & Materials",
    "DCC":"Support Services",
    "DGE":"Beverages",
    "DLG":"Nonlife Insurance",
    "EVR":"Industrial Metals & Mining",
    "EXPN":"Support Services",
    "EZJ":"Travel & Leisure",
    "FERG":"Support Services",
    "FRES":"Mining",
    "GFS":"Support Services",
    "GKN":"Automobiles & Parts",
    "GLEN":"Mining",
    "GSK":"Pharmaceuticals & Biotechnology",
    "HL":"Financial Services",
    "HLMA":"Electronic & Electrical Equipment",
    "HMSO":"Real Estate Investment Trusts",
    "HSBA":"Banks",
    "IAG":"Travel & Leisure",
    "IHG":"Travel & Leisure",
    "III":"Financial Services",
    "IMB":"Tobacco",
    "INF":"Media",
    "ITRK":"Support Services",
    "ITV":"Media",
    "JE":"General Retailers",
    "JMAT":"Chemicals",
    "KGF":"General Retailers",
    "LAND":"Real Estate Investment Trusts",
    "LGEN":"Life Insurance",
    "LLOY":"Banks",
    "LSE":"Financial Services",
    "MCRO":"Software & Computer Services",
    "MDC":"Health Care Equipment & Services",
    "MKS":"General Retailers",
    "MNDI":"Forestry & Paper",
    "MRW":"Food & Drug Retailers",
    "NG":"Gas, Water & Multiutilities",
    "NMC":"Health Care Equipment & Services",
    "NXT":"General Retailers",
    "OML":"Life Insurance",
    "PPB":"Travel & Leisure",
    "PRU":"Life Insurance",
    "PSN":"Household Goods & Home Construction",
    "PSON":"Media",
    "RB":"Household Goods & Home Construction",
    "RBS":"Banks",
    "RDSA":"Oil & Gas Producers",
    "RDSB":"Oil & Gas Producers",
    "REL":"Media",
    "RIO":"Mining",
    "RR":"Aerospace & Defense",
    "RRS":"Mining",
    "RSA":"Nonlife Insurance",
    "RTO":"Support Services",
    "SBRY":"Food & Drug Retailers",
    "SDR":"Financial Services",
    "SGE":"Software & Computer Services",
    "SGRO":"Real Estate Investment Trusts",
    "SHP":"Pharmaceuticals & Biotechnology",
    "SKG":"General Industrials",
    "SKY":"Media",
    "SLA":"Financial Services",
    "SMDS":"General Industrials",
    "SMIN":"General Industrials",
    "SMT":"Equity Investment Instruments",
    "SN":"Health Care Equipment & Services",
    "SSE":"Electricity",
    "STAN":"Banks",
    "STJ":"Life Insurance",
    "SVT":"Gas, Water & Multiutilities",
    "TSCO":"Food & Drug Retailers",
    "TUI":"Travel & Leisure",
    "TW":"Household Goods & Home Construction",
    "ULVR":"Personal Goods",
    "UU":"Gas, Water & Multiutilities",
    "VOD":"Mobile Telecommunications",
    "WPP":"Media",
    "WTB":"Retail hospitality"
}

code_name = { # Translates code to name
    "III":"3i",
    "ADM":"Admiral Group",
    "AAL":"Anglo American plc",
    "ANTO":"Antofagasta",
    "AHT":"Ashtead Group",
    "ABF":"Associated British Foods",
    "AZN":"AstraZeneca",
    "AV":"Aviva",
    "BA":"BAE Systems",
    "BARC":"Barclays",
    "BDEV":"Barratt Developments",
    "BKG":"Berkeley Group Holdings",
    "BLT":"BHP",
    "BP":"BP",
    "BATS":"British American Tobacco",
    "BLND":"British Land",
    "BTA":"BT Group",
    "BNZL":"Bunzl",
    "BRBY":"Burberry",
    "CCL":"Carnival Corporation & plc",
    "CNA":"Centrica",
    "CCH":"Coca-Cola HBC AG",
    "CPG":"Compass Group",
    "CRH":"CRH plc",
    "CRDA":"Croda International",
    "DCC":"DCC plc",
    "DGE":"Diageo",
    "DLG":"Direct Line Group",
    "EZJ":"easyJet",
    "EVR":"Evraz",
    "EXPN":"Experian",
    "FERG":"Ferguson plc",
    "FRES":"Fresnillo plc",
    "GFS":"G4S",
    "GKN":"GKN",
    "GSK":"GlaxoSmithKline",
    "GLEN":"Glencore",
    "HLMA":"Halma",
    "HMSO":"Hammerson",
    "HL":"Hargreaves Lansdown",
    "HSBA":"HSBC",
    "IMB":"Imperial Brands",
    "INF":"Informa",
    "IHG":"InterContinental Hotels Group",
    "IAG":"International Airlines Group",
    "ITRK":"Intertek",
    "ITV":"ITV plc",
    "JMAT":"Johnson Matthey",
    "JE":"Just Eat",
    "KGF":"Kingfisher plc",
    "LAND":"Land Securities",
    "LGEN":"Legal & General",
    "LLOY":"Lloyds Banking Group",
    "LSE":"London Stock Exchange Group",
    "MKS":"Marks & Spencer",
    "MDC":"Mediclinic International",
    "MCRO":"Micro Focus",
    "MNDI":"Mondi",
    "MRW":"Morrisons",
    "NG":"National Grid plc",
    "NXT":"Next plc",
    "NMC":"NMC Health",
    "OML":"Old Mutual",
    "PPB":"Paddy Power Betfair",
    "PSON":"Pearson PLC",
    "PSN":"Persimmon plc",
    "PRU":"Prudential plc",
    "RRS":"Randgold Resources",
    "RB":"Reckitt Benckiser",
    "REL":"RELX Group",
    "RTO":"Rentokil Initial",
    "RIO":"Rio Tinto Group",
    "RR":"Rolls-Royce Holdings",
    "RBS":"The Royal Bank of Scotland Group",
    "RDSA":"Royal Dutch Shell A",
    "RDSB":"Royal Dutch Shell B",
    "RSA":"RSA Insurance Group",
    "SGE":"Sage Group",
    "SBRY":"Sainsbury's",
    "SDR":"Schroders",
    "SMT":"Scottish Mortgage Investment Trust",
    "SGRO":"Segro",
    "SVT":"Severn Trent",
    "SHP":"Shire plc",
    "SKY":"Sky plc",
    "SN":"Smith & Nephew",
    "SMDS":"Smith, DS",
    "SMIN":"Smiths Group",
    "SKG":"Smurfit Kappa",
    "SSE":"SSE plc",
    "STAN":"Standard Chartered",
    "SLA":"Standard Life Aberdeen",
    "STJ":"St James's Place plc",
    "TW":"Taylor Wimpey",
    "TSCO":"Tesco",
    "TUI":"TUI Group",
    "ULVR":"Unilever",
    "UU":"United Utilities",
    "VOD":"Vodafone Group",
    "WTB":"Whitbread",
    "WPP":"WPP plc"
}
